function cfg = recompute_pareto_lambda(cfg)
% RECOMPUTE_PARETO_LAMBDA: Pareto On-Off 트래픽의 lambda 관련 파생값 업데이트
%
% 입력:
%   cfg - Pareto On-Off 파라미터(mu_on, mu_off, L_cell 등)가 포함된 설정 구조체
%
% 출력:
%   cfg - lambda 및 관련 파생 필드가 갱신된 설정 구조체
%
% 계산 내용:
%   - rho (On 비율)
%   - 네트워크 평균 lambda (평균 부하 기준)
%   - On-state lambda (Pareto On 단계에서 사용되는 포아송 레이트)
%   - 단말당 평균/On-state lambda
%
% ⚠️  cfg.numRU_SA, cfg.data_rate_per_RU, cfg.size_MPDU, cfg.num_STAs, cfg.L_cell
%     가 사전에 정의되어 있어야 합니다.
%
% 예외 처리:
%   - mu_on + mu_off == 0 인 경우, 기본값을 유지하고 경고 출력
%
% 작성자: Auto-generated by assistant

    cycle_time = cfg.mu_on + cfg.mu_off;
    if cycle_time <= 0
        warning('recompute_pareto_lambda: mu_on + mu_off must be > 0. Values kept unchanged.');
        cfg.rho = 0.0;
        cfg.lambda_avg_network = 0.0;
        cfg.lambda_on_network = 0.0;
        cfg.lambda_avg_per_sta = 0.0;
        cfg.lambda = 0.0;
        return;
    end

    cfg.rho = cfg.mu_on / cycle_time;

    total_capacity = cfg.numRU_SA * cfg.data_rate_per_RU; % [bps]
    packet_bits = cfg.size_MPDU * 8;

    cfg.lambda_avg_network = cfg.L_cell * total_capacity / packet_bits;

    if cfg.rho > 0
        cfg.lambda_on_network = cfg.lambda_avg_network / cfg.rho;
    else
        cfg.lambda_on_network = 0.0;
    end

    cfg.lambda_avg_per_sta = cfg.lambda_avg_network / cfg.num_STAs;
    cfg.lambda_on_per_sta = cfg.lambda_on_network / cfg.num_STAs;

    % 기존 코드와 호환성을 위해 필드 유지
    cfg.lambda_network = cfg.lambda_avg_network;
    cfg.lambda = cfg.lambda_on_per_sta;
end